source/accounts/urls.py
from django.urls import path
from .views import register_view, UserDetailView, UserChangeView, UserChangePasswordView,logout_view,login_view

app_name = 'accounts'


urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('create/', register_view, name='create'),
    path('profile/<pk>/', UserDetailView.as_view(), name='user_detail'),
    path('profile/<pk>/edit/', UserChangeView.as_view(), name='user_update'),
    path('profile/<pk>/change-password/', UserChangePasswordView.as_view(), name='user_change_password'),

]

source/main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/accounts/models.py
from django.contrib.auth.models import User
from django.db import models



class UserProfile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE, related_name='profile')
    avatar = models.ImageField(null=True, blank=True, upload_to='user_pics', verbose_name='Аватар')
    def __str__(self):
        return self.user
    class Meta:
        verbose_name = 'Профиль'
        verbose_name_plural = 'Профили'
# Create your models here.

source/accounts/forms.py
from django.contrib.auth.models import User

from django import forms
from django.core.exceptions import ValidationError

from accounts.models import UserProfile


class UserCreationForm(forms.ModelForm):

    password = forms.CharField(label="Пароль", strip=False,
                               widget=forms.PasswordInput(attrs={'placeholder': u'Enter password'}))
    password_confirm = forms.CharField(label="Подтвердите пароль",
                                       widget=forms.PasswordInput(attrs={'placeholder': u'Enter password confirm'}),
                                        strip=False)
    email = forms.EmailField(label='email', required=True,
                             widget=forms.EmailInput(attrs={'placeholder': u'Enter email'}))

    def clean_password_confirm(self):

        password = self.cleaned_data.get("password")

        password_confirm = self.cleaned_data.get("password_confirm")

        if password and password_confirm and password != password_confirm:
            raise forms.ValidationError('Пароли не совпадают!')

        return password_confirm

    def save(self, commit=True):

        user = super().save(commit=False)

        user.set_password(self.cleaned_data["password"])

        if commit:
            user.save()

        user.save()

        UserProfile.objects.create(user=user)

        return user

    def clean(self):
        super().clean()
        first_name = self.cleaned_data.get('first_name')
        last_name = self.cleaned_data.get('last_name')
        if not first_name and not last_name:
            raise ValidationError('Error, first or last name must be filled', code='name_is_empty')
        return self.cleaned_data

    def clean_email(self):
        email = self.cleaned_data.get('email')
        try:
            User.objects.get(email=email)
            raise ValidationError('Email already registered.', code='email_registered')
        except User.DoesNotExist:
            return email

    class Meta:

        model = User

        fields = ['username', 'password', 'password_confirm', 'first_name', 'last_name', 'email']

        widgets = {
            'username': forms.TextInput(attrs={'placeholder': u'Enter username'}),
            'first_name': forms.TextInput(attrs={'placeholder': u'Enter first name'}),
            'last_name': forms.TextInput(attrs={'placeholder': u'Enter first name'})
        }

class UserChangeForm(forms.ModelForm):
        def __init__(self, **kwargs):
            super().__init__(**kwargs)
            self.fields['avatar'] = forms.ImageField(required=False, label="Avatar")
        # avatar = forms.ImageField(label='Аватар', required=False)

        def get_initial_for_field(self, field, field_name):
            if field_name in self.Meta.profile_fields:
                try:
                    return getattr(self.instance.profile, field_name)
                except UserProfile.DoesNotExist:
                    return None
            return super().get_initial_for_field(field, field_name)

        def save(self, commit=True):
            user = super().save(commit)
            self.save_profile(commit)
            return user

        def save_profile(self, commit=True):
            try:
                profile = self.instance.profile
            except UserProfile.DoesNotExist:
                profile = UserProfile.objects.create(user=self.instance)
            for field in self.Meta.profile_fields:
                setattr(profile, field, self.cleaned_data[field])
            if not profile.avatar:
                profile.avatar = None
            if commit:
                profile.save()

        class Meta:
            model = User
            fields = ['first_name', 'last_name', 'email']
            profile_fields = ['avatar']
            labels = {'first_name': 'Имя', 'last_name': 'Фамилия', 'email': 'Email'}

class UserChangePasswordForm(forms.ModelForm):
    password = forms.CharField(max_length=100, required=True, label='New Password',
                               widget=forms.PasswordInput)
    password_confirm = forms.CharField(max_length=100, required=True, label='New Password confirm',
                                       widget=forms.PasswordInput)
    old_password = forms.CharField(max_length=100, required=True, label='Old Password',
                                   widget=forms.PasswordInput)

    def clean_old_password(self):
        old_password = self.cleaned_data.get('old_password')
        user = self.instance
        if not user.check_password(old_password):
            raise ValidationError('Invalid password.', code='invalid_password')
        return old_password



    def clean(self):
        super().clean()
        password_1 = self.cleaned_data.get('password')
        password_2 = self.cleaned_data.get('password_confirm')
        if password_1 != password_2:
            raise ValidationError('Passwords do not match.', code='passwords_do_not_match')
        return self.cleaned_data

    def save(self, commit=True):
        user = self.instance
        user.set_password(self.cleaned_data.get('password'))
        if commit:
            user.save()
        return user

    class Meta:
        model = User
        fields = ['password', 'password_confirm', 'old_password']

source/accounts/views.py
from accounts.forms import UserChangeForm
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from django.views.generic import DetailView, UpdateView, ListView

from webapp.models import File
from .forms import UserCreationForm, UserChangePasswordForm



def login_view(request):
    context = {}
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('webapp:index')
        else:
            context['has_error'] = True
    return render(request, 'registration/login.html', context=context)


def logout_view(request):
    logout(request)
    return redirect('webapp:index')

def register_view(request, *args, **kwargs):
    if request.method == 'POST':
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('webapp:index')
    else:
        form = UserCreationForm()
    return render(request, 'user_create.html', context={'form': form})


class UserDetailView(DetailView):
    model = User
    template_name = 'user_detail.html'
    context_object_name = 'user_obj'

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        user = self.object
        if not self.request.user == user:
            files = File.objects.all().filter(author=user,access='shared').order_by('-created_at')
            context['files'] = files
        if self.request.user == user:
            files = File.objects.all().filter(author=user).order_by('-created_at')
            context['files'] = files
        return context



class UserChangeView(UserPassesTestMixin, UpdateView):
    model = User
    template_name = 'user_update.html'
    context_object_name = 'user_obj'
    form_class = UserChangeForm

    def test_func(self):
        return self.get_object() == self.request.user



    def get_success_url(self):
        return reverse('accounts:user_detail', kwargs={'pk': self.object.pk})



class UserChangePasswordView(UserPassesTestMixin, UpdateView):
    model = User
    template_name = 'user_change_password.html'
    form_class = UserChangePasswordForm
    context_object_name = 'user_obj'

    def test_func(self):
        return self.get_object() == self.request.user

    def get_success_url(self):
        return reverse('accounts:login')



# Create your views here.

source/accounts/templates/user_change_password.html
{% extends 'base.html' %}
{% block title %}{{ user_obj.username }}{% endblock %}
{% block menu %}
    {% if user_obj == request.user %}
        <li><a href="{% url 'accounts:user_detail' user_obj.pk %}" class="nav-link">View</a></li>
        <li><a href="{% url 'accounts:user_update' user_obj.pk %}" class="nav-link">Edit Profile</a></li>
    {% endif %}
{% endblock %}
{% block content %}
    <h1>Change Password: {{ user_obj.username }}</h1>
    <form action="{% url 'accounts:user_change_password' user_obj.pk %}" method="post">
        {% include 'partial/form.html' with button_text="Save" %}
    </form>
{% endblock %}

source/accounts/templates/user_create.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block styles %}
    <link rel="stylesheet" href="{% static 'accounts/css/style.css' %}">
{% endblock %}
{% block content %}
    <title>Регистрация</title>
<body>
    <div class="container">
        <h1>Регистрация</h1>
            <form action="{% url 'accounts:create' %}" method="post" class="text-center">
                {% csrf_token %}
                {% for error in form.non_field_errors %}
                    <p class="form-error">{{ error }}</p>
                {% endfor %}
                {% for field in form %}
                    <div class="form-group">
                    <div>
                        <label for="{{ field.id_for_label }}" class="registration
                        {% if field.field.required %}required{% endif %}">{{ field.label }}</label>
                    </div>
                        {% if field.errors %}
                            {{ field }}
                            {% for error in field.errors %}
                                <p class="form-error">{{ error }}</p>
                            {% endfor %}
                        {% else %}
                        {{ field }}
                    {% endif %}
                    </div>
                    {% endfor %}
                <button type="submit">Зарегистрироваться</button>
            </form>
        </div>
{% endblock %}

source/accounts/templates/user_detail.html
{% extends 'base.html' %}
{% block menu %}
{% if user_obj == request.user %}
        <li><a href="{% url "accounts:user_update" user_obj.pk %}" class="nav-link">Edit Profile</a></li>
        <li><a href="{% url 'accounts:user_change_password' user_obj.pk %}" class="nav-link">Change Password</a></li>
{% endif %}
{% endblock %}
{% block title %}{{ user_obj.username }}{% endblock %}
{% block content %}
    <h1>Profile: {{ user_obj.username }}</h1>
    {% if user_obj.profile.avatar %}
        <img class="avatar" src="{{ user_obj.profile.avatar.url }}" width="250" height="250" alt="user picture">
    {% endif %}
    {% if user_obj.first_name %}
        <p>First Name: <b>{{ user_obj.first_name }}</b></p>
    {% endif %}
    {% if user_obj.email %}
        <p>Email: {{ user_obj.email }}</p>
    {% endif %}
    <h2>Users files</h2>
    <div class="row">
    {% for file in files %}
            <div class="col col-3">
                {% include "partial/partial_card.html" %}
            </div>
        <hr>
    {% endfor %}
    </div>
{% endblock %}

source/accounts/templates/user_update.html
{% extends 'base.html' %}
{% block title %}{{ user_obj.username }}{% endblock %}
{% block menu %}
    {% if user_obj == request.user %}
        <li><a href="{% url 'accounts:user_detail' user_obj.pk %}" class="nav-link">
            View</a></li>
        <li><a href="{% url 'accounts:user_change_password' user_obj.pk %}" class="nav-link">
            Change Password</a></li>
    {% endif %}
{% endblock %}
{% block content %}
    <h1>Edit Profile: {{ user_obj.username }}</h1>
    <form action="{% url "accounts:user_update" user_obj.pk %}" method="post" enctype="multipart/form-data">
        {% include 'partial/form.html' with button_text="Update" %}
    </form>
{% endblock %}

source/accounts/templates/users_list.html
{% extends 'base.html' %}
{% block content %}
    <h1 class="mt-3">Добро пожаловать</h1>
    <div class="row">
        {% for user_obj in users %}
            <div class="col-12 col-sm-6 col-md-4 col-lg-3 mt-3">
                <div class="card">
                    <div class="card-body">
                        <h2 class="card-text card-link">
                            <a href="{% url 'accounts:user_detail' user_obj.pk %}">{{ user_obj.username }}</a>
                        </h2>
                    </div>
                </div>
            </div>
        {% endfor %}
        {% if is_paginated %}
            {% include 'partial/pagination.html' %}
        {% endif %}
    </div>
{% endblock %}