source/accounts/urls.py
from django.urls import path
from .views import register_view, UserDetailView, UserChangeView, UserChangePasswordView,logout_view,login_view

app_name = 'accounts'


urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('create/', register_view, name='create'),
    path('profile/<pk>/', UserDetailView.as_view(), name='user_detail'),
    path('profile/<pk>/edit/', UserChangeView.as_view(), name='user_update'),
    path('profile/<pk>/change-password/', UserChangePasswordView.as_view(), name='user_change_password'),

]

source/main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path

from webapp.views import FileListView,FileDeleteView,FileUpdateView,FileDetailView,FileCreateView,AddToPrivate,\
    DeletePrivate

urlpatterns = [
    path('', FileListView.as_view(), name='index'),
    path('file/create/', FileCreateView.as_view(), name='file_create'),
    path('file/detail/<int:pk>/', FileDetailView.as_view(), name='file_detail'),
    path('file/update/<int:pk>/', FileUpdateView.as_view(), name='file_update'),
    path('file/delete/<int:pk>/', FileDeleteView.as_view(), name='file_delete'),
    path('user/add/private/', AddToPrivate.as_view(), name='private_create'),
    path('user/delete/private/', DeletePrivate.as_view(),name='private_delete')
    ]

app_name = 'webapp'

source/webapp/models.py
from django.contrib.auth.models import User
from django.db import models


ACCESS_CHOICES = [
    ('shared', 'общий'),
    ('secured', 'скрытый'),
    ('private', 'приватный')
]

class File(models.Model):
    file = models.FileField(upload_to='uploads/files',null=False,blank=False,
                                verbose_name='Задание')
    name = models.CharField(max_length=2500, null=False, blank=False, verbose_name='Описание')
    author = models.ForeignKey(User, on_delete=models.PROTECT, related_name='file_author',
                               null=True, blank=True, verbose_name='Автор')
    access = models.CharField(max_length=25,choices=ACCESS_CHOICES, default=ACCESS_CHOICES[0][0], verbose_name='Доступ',
                            null=False,blank=False)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Время создания')


class PrivateFile(models.Model):
    file = models.ForeignKey(File,on_delete=models.PROTECT,related_name='private_file',null=False,blank=False)
    accesed_user = models.ForeignKey(User,on_delete=models.PROTECT,related_name='private_accessed_user',null=False,
                                     blank=False)

# Create your models here.

source/webapp/forms.py
from django import forms

from webapp.models import File


class FileForm(forms.ModelForm):

    class Meta:
        model = File
        exclude = ['author', 'created_at', 'access']


class AuthFileForm(forms.ModelForm):

    class Meta:
        model = File
        exclude = ['created_at','author']

class SimpleSearchForm(forms.Form):
    search = forms.CharField(max_length=100, required=False, label='Найти')

source/webapp/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.core.exceptions import PermissionDenied
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView, ListView
from django.utils.http import urlencode
from django.views.generic.base import View

from webapp.forms import FileForm, SimpleSearchForm,AuthFileForm
from webapp.models import File, PrivateFile


class FileListView(ListView):

    model = File
    template_name = 'file/list.html'
    context_object_name = 'files'
    ordering = ['-created_at']
    paginate_by = 10
    paginate_orphans = 1

    def get(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(access='shared')
        if self.search_value:
            queryset = queryset.filter(
                Q(name__icontains=self.search_value)
            )
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['form'] = self.form
        if self.search_value:
            context['query'] = urlencode({'search': self.search_value})
        return context

    def get_search_form(self):
        return SimpleSearchForm(data=self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data['search']
        return None


class FileDetailView(DetailView):

    model = File
    template_name = 'file/detail.html'
    context_object_name = 'file'


class FileCreateView(CreateView):

    model = File
    form_class = FileForm
    template_name = 'file/create.html'

    def get_form_class(self):
        if self.request.user.is_authenticated:
            return AuthFileForm
        return FileForm

    def form_valid(self, form):
        if self.request.user.is_authenticated:
            form.instance.author = self.request.user
        if not self.request.user.is_authenticated:
            form.instance.author = None
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('webapp:file_detail', kwargs={'pk': self.object.pk})

class FileUpdateView(UpdateView):

    model = File
    form_class = FileForm
    context_object_name = 'file'
    template_name = 'file/update.html'

    def get_form_class(self):
        if self.request.user.is_authenticated:
            return AuthFileForm
        return FileForm

    def get_object(self, queryset=None):
        file = File.objects.get(pk=self.kwargs.get('pk'))
        return file

    def dispatch(self, request, *args, **kwargs):
        file = self.get_object()
        if self.request.user == file.author:
            return super().dispatch(request, *args, **kwargs)
        if not request.user.has_perm('webapp.change_file'):
            raise PermissionDenied('403 Forbidden')
        return super().dispatch(request, *args, **kwargs)



class FileDeleteView(DeleteView):

    model = File
    template_name = 'file/delete.html'
    success_url = reverse_lazy('webapp:index')

    def get_object(self, queryset=None):
        file = File.objects.get(pk=self.kwargs.get('pk'))
        return file

    def dispatch(self, request, *args, **kwargs):
        file = self.get_object()
        if self.request.user == file.author:
            return super().dispatch(request, *args, **kwargs)
        if not request.user.has_perm('webapp.delete_file'):
            raise PermissionDenied('403 Forbidden')
        return super().dispatch(request, *args, **kwargs)

class AddToPrivate(LoginRequiredMixin, View):

    def post(self, request, *args, **kwargs):
        user = request.POST.get('username')
        file = request.POST.get('file_id')
        print(file, user)
        try:
            file = File.objects.get(pk=file)
            real_user = User.objects.get(username=user)
            private = PrivateFile.objects.get_or_create(accesed_user=real_user, file=file)
            private = private[0]
            return JsonResponse({'pk': private.pk, 'user_pk': real_user.pk,'username':real_user.username})
        except User.DoesNotExist:
            return JsonResponse({'message': 'user does not exist'})


class DeletePrivate(LoginRequiredMixin, View):
    def post(self,request):
        user = request.POST.get('user')
        file = request.POST.get('file')
        try:
            file = File.objects.get(pk=file)
            real_user = User.objects.get(pk=user)
            PrivateFile.objects.delete(accesed_user=real_user, file=file)
            return JsonResponse({'user_pk': real_user.pk})
        except User.DoesNotExist:
            return JsonResponse({'message': 'user does not exist'})

source/webapp/templates/base.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}Issue-Tracker{% endblock %}</title>
    {% block styles %}{% endblock %}
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
   <link rel="stylesheet" href="{% static 'css/style.css' %}">
  </head>
  <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav w-100">
                    <li class="nav-item">
                        <a href="{% url 'webapp:index' %}" class="nav-link">Home</a>
                    </li>
                    <li>
                        <a href="{% url 'webapp:file_create' %}" class="nav-link">Create file</a>
                    </li>
                {% if user.is_authenticated %}
                {% block menu_links %}{% endblock %}
                <li class="menu-right">
                    <a href="{% url 'accounts:logout' %}" class="nav-link">
                        Выход
                    </a>
                </li>
                <li>
                    <a href="{% url 'accounts:user_detail' request.user.pk %}" class="nav-link">
                        Привет, {{ request.user }}!
                    </a>
                </li>
            {% else %}
                <li class="menu-right">
                    <a href="{% url 'accounts:login' %}" class="nav-link">
                        Вход
                    </a>
                </li>
                <li class="menu-right">
                    <a href="{% url 'accounts:create' %}" class="nav-link">
                        Регистрация
                    </a>
                </li>
                <li>
            </li>
            {% endif %}
                    {% block menu %}{% endblock %}
                </ul>
            </div>
        </nav>
        <div class="container">
            {% block content %}{% endblock %}
        </div>

        <script src="{% static 'js/main.js' %}"></script>
        {% block scripts %}{% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>