source/accounts/urls.py
from django.urls import path
from .views import register_view, UserDetailView, UserChangeView, UserChangePasswordView,logout_view,login_view

app_name = 'accounts'


urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('create/', register_view, name='create'),
    path('profile/<pk>/', UserDetailView.as_view(), name='user_detail'),
    path('profile/<pk>/edit/', UserChangeView.as_view(), name='user_update'),
    path('profile/<pk>/change-password/', UserChangePasswordView.as_view(), name='user_change_password'),

]

source/main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path

from webapp.views import FileListView,FileDeleteView,FileUpdateView,FileDetailView,FileCreateView,AddToPrivate,\
    DeletePrivate

urlpatterns = [
    path('', FileListView.as_view(), name='index'),
    path('file/create/', FileCreateView.as_view(), name='file_create'),
    path('file/detail/<int:pk>/', FileDetailView.as_view(), name='file_detail'),
    path('file/update/<int:pk>/', FileUpdateView.as_view(), name='file_update'),
    path('file/delete/<int:pk>/', FileDeleteView.as_view(), name='file_delete'),
    path('user/add/private/', AddToPrivate.as_view(), name='private_create'),
    path('user/delete/private/', DeletePrivate.as_view(),name='private_delete')
    ]

app_name = 'webapp'

source/webapp/models.py
from django.contrib.auth.models import User
from django.db import models


ACCESS_CHOICES = [
    ('shared', 'общий'),
    ('secured', 'скрытый'),
    ('private', 'приватный')
]

class File(models.Model):
    file = models.FileField(upload_to='uploads/files',null=False,blank=False,
                                verbose_name='Задание')
    name = models.CharField(max_length=2500, null=False, blank=False, verbose_name='Описание')
    author = models.ForeignKey(User, on_delete=models.PROTECT, related_name='file_author',
                               null=True, blank=True, verbose_name='Автор')
    access = models.CharField(max_length=25,choices=ACCESS_CHOICES, default=ACCESS_CHOICES[0][0], verbose_name='Доступ',
                            null=False,blank=False)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Время создания')


class PrivateFile(models.Model):
    file = models.ForeignKey(File,on_delete=models.PROTECT,related_name='private_file',null=False,blank=False)
    accesed_user = models.ForeignKey(User,on_delete=models.PROTECT,related_name='private_accessed_user',null=False,
                                     blank=False)

# Create your models here.

source/webapp/forms.py
from django import forms

from webapp.models import File


class FileForm(forms.ModelForm):

    class Meta:
        model = File
        exclude = ['author', 'created_at', 'access']


class AuthFileForm(forms.ModelForm):

    class Meta:
        model = File
        exclude = ['created_at','author']

class SimpleSearchForm(forms.Form):
    search = forms.CharField(max_length=100, required=False, label='Найти')

source/webapp/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.core.exceptions import PermissionDenied
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView, ListView
from django.utils.http import urlencode
from django.views.generic.base import View

from webapp.forms import FileForm, SimpleSearchForm,AuthFileForm
from webapp.models import File, PrivateFile


class FileListView(ListView):

    model = File
    template_name = 'file/list.html'
    context_object_name = 'files'
    ordering = ['-created_at']
    paginate_by = 10
    paginate_orphans = 1

    def get(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(access='shared')
        if self.search_value:
            queryset = queryset.filter(
                Q(name__icontains=self.search_value)
            )
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['form'] = self.form
        if self.search_value:
            context['query'] = urlencode({'search': self.search_value})
        return context

    def get_search_form(self):
        return SimpleSearchForm(data=self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data['search']
        return None


class FileDetailView(DetailView):

    model = File
    template_name = 'file/detail.html'
    context_object_name = 'file'


class FileCreateView(CreateView):

    model = File
    form_class = FileForm
    template_name = 'file/create.html'

    def get_form_class(self):
        if self.request.user.is_authenticated:
            return AuthFileForm
        return FileForm

    def form_valid(self, form):
        if self.request.user.is_authenticated:
            form.instance.author = self.request.user
        if not self.request.user.is_authenticated:
            form.instance.author = None
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('webapp:file_detail', kwargs={'pk': self.object.pk})

class FileUpdateView(UpdateView):

    model = File
    form_class = FileForm
    context_object_name = 'file'
    template_name = 'file/update.html'

    def get_form_class(self):
        if self.request.user.is_authenticated:
            return AuthFileForm
        return FileForm

    def get_object(self, queryset=None):
        file = File.objects.get(pk=self.kwargs.get('pk'))
        return file

    def dispatch(self, request, *args, **kwargs):
        file = self.get_object()
        if self.request.user == file.author:
            return super().dispatch(request, *args, **kwargs)
        if not request.user.has_perm('webapp.change_file'):
            raise PermissionDenied('403 Forbidden')
        return super().dispatch(request, *args, **kwargs)



class FileDeleteView(DeleteView):

    model = File
    template_name = 'file/delete.html'
    success_url = reverse_lazy('webapp:index')

    def get_object(self, queryset=None):
        file = File.objects.get(pk=self.kwargs.get('pk'))
        return file

    def dispatch(self, request, *args, **kwargs):
        file = self.get_object()
        if self.request.user == file.author:
            return super().dispatch(request, *args, **kwargs)
        if not request.user.has_perm('webapp.delete_file'):
            raise PermissionDenied('403 Forbidden')
        return super().dispatch(request, *args, **kwargs)

class AddToPrivate(LoginRequiredMixin, View):

    def post(self, request, *args, **kwargs):
        user = request.POST.get('username')
        file = request.POST.get('file_id')
        print(file, user)
        try:
            file = File.objects.get(pk=file)
            real_user = User.objects.get(username=user)
            private = PrivateFile.objects.get_or_create(accesed_user=real_user, file=file)
            private = private[0]
            return JsonResponse({'pk': private.pk, 'user_pk': real_user.pk,'username':real_user.username})
        except User.DoesNotExist:
            return JsonResponse({'message': 'user does not exist'})


class DeletePrivate(LoginRequiredMixin, View):
    def post(self,request):
        user = request.POST.get('user')
        file = request.POST.get('file')
        try:
            file = File.objects.get(pk=file)
            real_user = User.objects.get(pk=user)
            PrivateFile.objects.delete(accesed_user=real_user, file=file)
            return JsonResponse({'user_pk': real_user.pk})
        except User.DoesNotExist:
            return JsonResponse({'message': 'user does not exist'})

source/webapp/templates/file/create.html
{% extends 'base.html' %}
{% block title %}Create announce{% endblock %}
{% block content %}
   <h1>Create Task</h1>
        <form method="POST" action="{% url "webapp:file_create" %}" enctype="multipart/form-data">
            {% csrf_token %}
                {% include 'partial/form.html' with button_text="Create" %}
        </form>
{% endblock %}

source/webapp/templates/file/delete.html
{% extends 'base.html' %}
{% block title %}Delete file{% endblock %}
{% block menu %}
{% endblock %}
{% block content %}
    <h1>Are you sure want to delete file?</h1>
        <form method="POST" action="{% url 'webapp:file_delete' file.pk %}" class="text-center">
            {% csrf_token %}
            <p><input type="submit" class = 'btn' value="Confirm"></p>
            <p><a href="{% url 'webapp:index'  %}" class = 'btn'>Cancel</a></p>
        </form>
{% endblock %}

source/webapp/templates/file/detail.html
{% extends 'base.html' %}
{% block menu %}
    {% if perms.webapp.change_file %}
        <li class="nav-item">
            <a href="{% url 'webapp:file_update' file.pk %}" class="nav-link">Update file</a>
        </li>
    {% elif request.user == file.author %}
        <li class="nav-item">
            <a href="{% url 'webapp:file_update' file.pk %}" class="nav-link">Update file</a>
        </li>
    {% endif %}
    {% if perms.webapp.delete_file %}
        <li>
            <a href="{% url 'webapp:file_delete' file.pk %}" class="nav-link">Delete file</a>
        </li>
    {% elif request.user == file.author %}
        <li>
            <a href="{% url 'webapp:file_delete' file.pk %}" class="nav-link">Delete file</a>
        </li>
    {% endif %}
{% endblock %}
{% block content %}
    {% if file.author %}
        <h5><a href="{% url "accounts:user_detail" file.author.pk %}">Добавил: {{ file.author }}</a></h5>
    {% else %}
        <h5>Добавил: Аноним</h5>
    {% endif %}
    {% if file.access == private or request.user == file.author %}
        <p><a href="{{ file.file.url }}" download >Загрузить файл</a></p>
    {% endif %}
    <p>{{ file.name }}</p>
    <p>  Был добавлен:   {{ file.created_at }}</p>
    <p> Доступ: {{ file.access }}</p>
    {% if file.access == 'private' or file.author == request.user %}
        {% for user in file.private_file.all %}
            <div id="add-users">
                <a href="{% url 'accounts:user_detail' user.accesed_user.pk %}">
                    {{ user.accesed_user.username }}
                </a>
                <a href="" class="btn btn-danger favorites-add" onclick="privateDelete(event, {{ file.pk }},
                        {{ user.accesed.pk }})">
                    delete
                </a>
            </div>
        {% endfor %}
    <div id="div-input">
        <input type="text" id="input">
        <a href="" class="btn btn-success favorites-add" onclick="favoritesAdd(event, {{ file.pk }})">Add</a>
    </div>
    {% endif %}
{% endblock %}
{% block scripts %}
    <script>
    function favoritesAdd(event, pk) {
            event.preventDefault();
            let block_append = $(`add-users`);
            console.log('start', pk);
            let csrftoken = getCookie('csrftoken');
            let user = $(`#input`).val();
            let data = {
                file_id: pk,
                username: user,
            };
            $.ajax({
                url: '/user/add/private/',
                method: 'post',
                data: data,
                dataType: 'json',
                headers: {
                    "X-CSRFToken": csrftoken
                },
                success: function (item) {
                    console.log('ok');
                    console.log(item);
                    username = item['username'];
                    url = `http://localhost:8000/accounts/profile/${item['user_pk']}/`;
                    console.log(block_append);
                    block_append.append(`<div><a href= ${url}>${username}</a></div>`)

                }
            });
        }

        function privateDelete(event, file_pk,user_pk) {
            event.preventDefault();
            console.log('start', file_pk,user_pk);
            let data = {
                'user': user_pk,
                'file': file_pk
                };
            let csrftoken = getCookie('csrftoken');
            $.ajax({
                url: '/user/delete/private/',
                method: 'post',
                data: data,
                dataType: 'json',
                headers: {
                    "X-CSRFToken": csrftoken
                },
                success: function (item) {
                    console.log('ok');
                }
            });

        }


        function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = cookies[i].trim();
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }


    </script>
{% endblock %}

source/webapp/templates/file/list.html
{% extends 'base.html' %}
{% load i18n %}
{% block menu %}
    <div class="search" style="padding-top: 7px">
        {% include 'partial/simple_search.html' %}
    </div>
{% endblock %}
{% block title %}Файлы{% endblock %}
{% block content %}
    <h1 class="text-center">Файлы</h1>
    <div class="row">
        {% for file in files %}
            <div class="col col-3">
                {% include "partial/partial_card.html" %}
            </div>
        {% endfor %}
    </div>
    {% if is_paginated %}
            {% include 'partial/pagination.html' %}
    {% endif %}
{% endblock %}

source/webapp/templates/file/update.html
{% extends 'base.html' %}
{% block title %}Update file{% endblock %}
{% block menu %}
{% endblock %}
{% block content %}
    <h1>Изменить данные файла</h1>
        <form method="POST" action="{% url 'webapp:file_update' file.pk %}">
            {% include 'partial/form.html' with button_text="Update" %}
        </form>
{% endblock %}